<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Compartilhado\Identity\" />
    <Folder Include="Modulos\" />
    <Folder Include="Modulos\ModuloCategoria\" />
    <Folder Include="Modulos\ModuloCurso\" />
    <Folder Include="Modulos\ModuloEtapa\" />
    <Folder Include="Modulos\ModuloInstituicao\" />
    <Folder Include="Modulos\ModuloNivelDeDificuldade\" />
  </ItemGroup>

</Project>
